version: '0.1.1.{build}'
branches:
  only:
    - /v0.1.1/
environment:
  matrix:
    - TOXENV: "py36"
      TOXPYTHON: "C:\\Python36-x64\\python.exe"
      PYTHON_HOME: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

    - TOXENV: "py35"
      TOXPYTHON: "C:\\Python35-x64\\python.exe"
      PYTHON_HOME: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"

    - TOXENV: "py34"
      TOXPYTHON: "C:\\Python34-x64\\python.exe"
      PYTHON_HOME: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"

    - TOXENV: "py27"
      TOXPYTHON: "C:\\Python27-x64\\python.exe"
      PYTHON_HOME: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"

    - TOXENV: "py27"
      TOXPYTHON: "C:\\Python27\\python.exe"
      PYTHON_HOME: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"

init:
  - "ECHO %TOXENV%"
  - "ECHO %TOXPYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
  - "%TOXPYTHON% C:/get-pip.py"
  - "%PYTHON_HOME%/Scripts/pip.exe install -r requirements-appveyor.txt"

build: false

test_script:
  - "%PYTHON_HOME%\\Scripts\\tox -e %TOXENV%"
